pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('big_data')
        MYSQL_ROOT_CREDS=credentials('mysql')
        VAULT_TOKEN_CREDS=credentials('token')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    options {
            timestamps()
            skipDefaultCheckout(true)
        }
    stages {
        stage('export env') {
            steps {
                sh 'export pass=$MYSQL_ROOT_CREDS_PSW && export token=$VAULT_TOKEN_CREDS_PSW'
				}
			}

        stage('check env') {
            steps {
                sh 'echo ${pass} && echo ${token}'
				}
			}
        

        stage('Clone github repository') {
            steps {
                cleanWs()
                sh 'git clone -b main https://github.com/liaoxin-a/big_data_lab3.git'
				}
			}

        stage('Checkout repo dir') {
            steps {
                sh 'cd big_data_lab2 && ls'
				}
			}

        
        stage('Login'){
            steps{
                sh 'docker login -u $DOCKERHUB_CREDS -p $DOCKERHUB_CREDS_PSW'
                }
            }

        stage('Create and run docker container') {
            steps {
                // sh 'cd big_data_lab2 && docker-compose up'
                script {
                    try {
                        sh 'cd big_data_lab2 && docker-compose build'
                        }

                    finally {
                    sh '''
                        cd big_data_lab2
                        docker-compose up -d
                        '''
                        }
				    }
                }
            }

        // use for multi containers:
        //docker exec %containerId% cd app && coverage run src/unit_tests/test_preprocess.py && coverage run -a src/unit_tests/test_training.py && coverage report -m
        //use for single container (with auth):
        //docker run --name big_data_web_1 cd app && coverage run src/unit_tests/test_preprocess.py && coverage run -a src/unit_tests/test_training.py && coverage report -m


        stage('Checkout coverage report'){
            steps{
                dir("big_data_lab2"){
                    sh '''
                    docker-compose logs -t --tail 10
                    '''
                }
            }
        }

        stage('Push'){
            steps{
                sh '''
                    docker push liaox1/big_data:2.0
                    docker push liaox1/db_yt8m:1.0  
                    '''
            }
        }
	}

    post {
        always {
            sh 'docker logout'
        }
    }
 
}